# Generated by Django 6.1.1 on 2026-09-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('profile_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='inspector.industry')),
                ('tags', models.ManyToManyField(blank=True, related_name='businesses', to='inspector.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True)),
                ('profile_text', models.TextField(blank=True)),
                ('discovery_target', models.TextField(blank=True, help_text='What we want to learn from this prospect.')),
                ('opening_question', models.TextField(blank=True, help_text='The initial question used to start discovery.')),
                ('big_3_questions', models.JSONField(blank=True, default=list, help_text="Three Mom Test-style questions for digging into the prospect's real workflow and problems.")),
                ('outreach_message', models.TextField(blank=True, help_text='AI-generated outreach message.')),
                ('research_notes', models.TextField(blank=True, help_text='AI research and hypotheses. Not confirmed customer findings.')),
                ('findings', models.TextField(blank=True, help_text='What was actually learned from talking to the prospect.')),
                ('notes', models.TextField(blank=True, help_text='Additional manual notes.')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('learned', 'Learned')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='inspector.business')),
            ],
        ),
    ]
