# Generated by Django 6.1.1 on 2026-09-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('learned', 'Learned'), ('ghosted', 'Ghosted'), ('weak informat', 'Weak Informant')], default='new', max_length=20),
        ),
    ]
