# Generated by Django 6.1.1 on 2026-09-08 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='big_3_questions',
            field=models.JSONField(blank=True, default=list, help_text="Three Mom Test-style questions for digging into the prospect's real workflow and problems."),
        ),
        migrations.AddField(
            model_name='prospect',
            name='research_notes',
            field=models.TextField(blank=True, help_text='AI research and hypotheses. Not confirmed customer findings.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='inspector.industry'),
        ),
        migrations.AlterField(
            model_name='business',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='inspector.tag'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='discovery_target',
            field=models.TextField(blank=True, help_text='What we want to learn from this prospect.'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='findings',
            field=models.TextField(blank=True, help_text='What was actually learned from talking to the prospect.'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional manual notes.'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='opening_question',
            field=models.TextField(blank=True, help_text='The initial question used to start discovery.'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='outreach_message',
            field=models.TextField(blank=True, help_text='AI-generated outreach message.'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='profile_text',
            field=models.TextField(blank=True),
        ),
    ]
