# Generated by Django 6.1.1 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_alter_prospect_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['-created_at'], name='inspector_p_created_aacc3e_idx'),
        ),
    ]
