# Generated by Django 6.1.1 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_prospectinput_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='linkedin_url',
            new_name='profile_url',
        ),
        migrations.AddField(
            model_name='prospectinput',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
    ]
